apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core
  annotations:
    description: AntiNex - AI Core - Celery Worker for Training and Making Predictions
    runtime: python3
  labels:
    app: core
    purpose: worker
    layer: backend
    ai.framework: keras
    ai.backend: tensorflow
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
      backend: enabled
  template:
    metadata:
      labels:
        app: core
        purpose: worker
        layer: backend
        ai.framework: keras
        ai.backend: tensorflow
        layer: backend
        backend: enabled
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: backend
                operator: In
                values:
                - enabled
      hostname: core
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-core:latest
        imagePullPolicy: Always
        name: core
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8.env &&
          export CORE_EXTRA_ARGS="--without-heartbeat --without-gossip" &&
          /opt/antinex/core/run-antinex-core.sh
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: core.db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: core.db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: core.db
              key: dbname
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: secret_key
        - name: S3_ADDRESS
          value: minio-service:9000
        - name: S3_REGION_NAME
          value: us-east-1
