apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core
  annotations:
    description: AntiNex - AI Core - Celery Worker for Training and Making Predictions
    runtime: python3
  labels:
    app: core
    purpose: worker
    layer: backend
    ai.framework: keras
    ai.backend: tensorflow
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
        purpose: worker
        layer: backend
        ai.framework: keras
        ai.backend: tensorflow
        layer: backend
    spec:
      hostname: core
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-core:latest
        imagePullPolicy: Always
        name: core
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/openshift-no-hostnames.env &&
          /opt/antinex/core/run-antinex-core.sh
        env:
        - name: ANTINEX_AUTH_URL
          value: redis://redis-master:6379/6
        - name: ANTINEX_RESULT_AUTH_URL
          value: redis://redis-master:6379/9
        - name: ANTINEX_CA_CERTS
        - name: ANTINEX_CERTFILE
        - name: ANTINEX_DELIVERY_MODE
          value: persistent
        - name: ANTINEX_EXCHANGE_NAME
          value: webapp.predict.requests
        - name: ANTINEX_EXCHANGE_TYPE
          value: topic
        - name: ANTINEX_KEYFILE
        - name: ANTINEX_QUEUE_NAME
          value: webapp.predict.requests
        - name: ANTINEX_TLS_PROTOCOL
        - name: ANTINEX_WORKER_ENABLED
          value: "1"
        - name: ANTINEX_WORKER_ONLY
          value: "0"
        - name: ANTINEX_WORKER_SSL_ENABLED
          value: "0"
        - name: CACHEOPS_ENABLED
          value: "1"
        - name: CELERY_ENABLED
          value: "1"
        - name: COLLECT_STATICS
          value: "1"
        - name: DJANGO_ALLOWED_HOSTS
          value: '*'
        - name: DJANGO_CONFIGURATION
          value: Development
        - name: DJANGO_DEBUG
          value: "yes"
        - name: DJANGO_SECRET_KEY
          value: supersecret
        - name: DJANGO_TEMPLATE_DEBUG
          value: "yes"
        - name: ENVIRONMENT
          value: Development
        - name: NUM_WORKERS
          value: "4"
        - name: POSTGRES_HOST
          value: postgres-primary
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: webapp
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: USE_ENV
          value: openshift-no-hostnames
        - name: USE_VENV
          value: /opt/venv
        - name: WEBAPP_HOST
          value: 0.0.0.0
        - name: WEBAPP_PORT
          value: "8010"
        - name: HTTP_X_FORWARDED_PROTOCOL_KEY
          value: HTTP_X_FORWARDED_PROTO
        - name: BROKER_URL
          value: redis://redis-master:6379/6
        - name: SHARED_DIR
          value: /opt/data
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: core
        - name: ENV_NAME
          value: k8
        - name: SHARED_LOG_CFG
          value: /opt/spylunking/spylunking/log/shared-logging.json
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: splunk-svc:8088
        - name: SPLUNK_API_ADDRESS
          value: splunk-svc:8089
        - name: SPLUNK_TCP_ADDRESS
          value: splunk-tcp-svc:1514
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_VERIFY
          value: "1"
        - name: SPLUNK_DEBUG
          value: "0"
