apiVersion: v1
kind: Secret
metadata:
  name: core.user
type: Opaque
data:
  # echo -n "trex" | base64
  username: dHJleA==
  # echo -n "123321" | base64
  password: MTIzMzIx
---
apiVersion: v1
kind: Secret
metadata:
  name: core.db
type: Opaque
data:
  # echo -n "antinex" | base64
  username: YW50aW5leA==
  # echo -n "antinex" | base64
  password: YW50aW5leA==
  # echo -n "webapp" | base64
  dbname: d2ViYXBw
---
apiVersion: v1
kind: Secret
metadata:
  name: core.redis
type: Opaque
data:
  # echo -n "123321" | base64
  password: MTIzMzIx
