apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  # echo -n "antinex" | base64
  username: YW50aW5leA==
  # echo -n "antinex" | base64
  password: YW50aW5leA==
  # echo -n "webapp" | base64
  dbname: d2ViYXBw
