apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    role: master
    storage: ceph
spec:
  storageClassName: ceph-rbd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: ceph-rbd
spec:
  storageClassName: ceph-rbd
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10M
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/testing"
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-mount
  labels:
    integration-test: busybox-mount
spec:
  volumes:
  - name: test-pv
    persistentVolumeClaim:
      claimName: test-pvc
  containers:
  - image: busybox:glibc
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "ls -l /testing;"]
    name: busybox
    volumeMounts:
    - mountPath: "/testing"
      name: test-pv
