apiVersion: v1
kind: Secret
metadata:
  name: splunk.user
type: Opaque
data:
  # echo -n "trex" | base64
  username: dHJleA==
  # echo -n "123321" | base64
  password: MTIzMzIx
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk.log
type: Opaque
data:
  # echo -n "antinex" | base64
  index: YW50aW5leA==
  # echo -n "splunk" | base64
  handler: c3BsdW5r
  # echo -n "1" | base64
  verify: MQ==
  # echo -n "0" | base64
  debug: MA==
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk.endpoints
type: Opaque
data:
  # echo -n "splunk-tcp-svc" | base64
  tcp_service: c3BsdW5rLXRjcC1zdmM=
  # echo -n "splunk-svc" | base64
  api_service: c3BsdW5rLXN2Yw==
  # echo -n "splunk-svc:8089" | base64
  api: c3BsdW5rLXN2Yzo4MDg5
  # echo -n "splunk-tcp-svc:1514" | base64
  tcp: c3BsdW5rLXRjcC1zdmM6MTUxNA==
  # echo -n "splunk-svc:8088" | base64
  hec: c3BsdW5rLXN2Yzo4MDg4
