apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configs-pv-claim
  labels:
    app: configs
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
