apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontendshared-pv-claim
  labels:
    app: frontend
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
