apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  annotations:
    description: AntiNex API Consumers - Celery Django Rest Framework Backend Worker
    runtime: python3
  labels:
    app: worker
    purpose: worker
    layer: backend
    messaging: redis
    cache: redis
    pubsub: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        purpose: worker
        layer: backend
        messaging: redis
        cache: redis
        pubsub: consumer
    spec:
      hostname: worker
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-worker:latest
        imagePullPolicy: Always
        name: worker
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/api &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          export WORKER_EXTRA_ARGS="--without-heartbeat --without-gossip" &&
          /opt/antinex/api/run-worker.sh &&
          tail -f /var/log/antinex/api/worker.log
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: worker.db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: worker.db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: worker.db
              key: dbname
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: worker
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: username
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: password
        - name: SPLUNK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: hec
        - name: SPLUNK_API_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: api
        - name: SPLUNK_TCP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: tcp
        - name: SPLUNK_INDEX
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: index
        - name: SPLUNK_HANDLER_NAME
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: handler
        - name: SPLUNK_VERIFY
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: verify
        - name: SPLUNK_DEBUG
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: debug
