apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  annotations:
    description: AntiNex API Consumers - Celery Django Rest Framework Backend Worker
    runtime: python3
  labels:
    app: worker
    purpose: worker
    layer: backend
    messaging: redis
    cache: redis
    pubsub: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        purpose: worker
        layer: backend
        messaging: redis
        cache: redis
        pubsub: consumer
    spec:
      hostname: worker
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-worker:latest
        imagePullPolicy: Always
        name: worker
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/api &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          /opt/antinex/api/run-worker.sh &&
          tail -f /var/log/antinex/api/worker.log
        env:
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_DB
          value: webapp
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: worker
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: splunk-svc:8088
        - name: SPLUNK_API_ADDRESS
          value: splunk-svc:8089
        - name: SPLUNK_TCP_ADDRESS
          value: splunk-tcp-svc:1514
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_VERIFY
          value: "1"
        - name: SPLUNK_DEBUG
          value: "0"
