apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  name: redis-pv
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  persistentVolumeReclaimPolicy: Retain
