apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2018-05-27T20:06:05Z
  name: redis-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30G
  nfs:
    path: /data/k8/redis
    server: localhost
  persistentVolumeReclaimPolicy: Retain
