apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  annotations:
    description: AntiNex API - Django REST Framework with JWT and Swagger - Celery Producer
    runtime: python3
  labels:
    antinex: api
    purpose: rest
    layer: rest
    auth: jwt
    toolchain: swagger
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        purpose: rest
        layer: rest
        auth: jwt
        toolchain: swagger
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      hostname: api
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-api:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8010
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/api &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          /opt/antinex/api/run-django.sh
        env:
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_DB
          value: webapp
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: api
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: splunk-svc:8088
        - name: SPLUNK_API_ADDRESS
          value: splunk-svc:8089
        - name: SPLUNK_TCP_ADDRESS
          value: splunk-tcp-svc:1514
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_VERIFY
          value: "1"
        - name: SPLUNK_DEBUG
          value: "0"
