apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  annotations:
    description: AntiNex API - Django REST Framework with JWT and Swagger - Celery Producer
    runtime: python3
  labels:
    antinex: api
    purpose: rest
    layer: rest
    auth: jwt
    toolchain: swagger
    messaging: redis
    cache: redis
    pubsub: publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      frontend: enabled
  template:
    metadata:
      labels:
        app: api
        purpose: rest
        layer: rest
        auth: jwt
        toolchain: swagger
        messaging: redis
        cache: redis
        pubsub: publisher
        frontend: enabled
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: frontend
                operator: In
                values:
                - enabled
      hostname: api
      restartPolicy: Always
      containers:
      - image: jayjohnson/antinex-api:latest
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8010
        resources: {}
        command:
        - /bin/bash
        - -c
        - cd /opt/antinex/api &&
          . /opt/venv/bin/activate &&
          source /opt/antinex/api/envs/k8-splunk.env &&
          /opt/antinex/api/run-django.sh
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api.webserver
              key: secret_key
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api.db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api.db
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: api.db
              key: dbname
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-access
              key: secret_key
        - name: S3_ADDRESS
          value: minio-service:9000
        - name: S3_REGION_NAME
          value: us-east-1
        - name: DEPLOY_CONFIG
          value: splunk
        - name: LOG_NAME
          value: api
        - name: ENV_NAME
          value: k8
        - name: SPLUNK_USER
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: username
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk.user
              key: password
        - name: SPLUNK_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: hec
        - name: SPLUNK_API_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: api
        - name: SPLUNK_TCP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: splunk.endpoints
              key: tcp
        - name: SPLUNK_INDEX
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: index
        - name: SPLUNK_HANDLER_NAME
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: handler
        - name: SPLUNK_VERIFY
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: verify
        - name: SPLUNK_DEBUG
          valueFrom:
            secretKeyRef:
              name: splunk.log
              key: debug
